# -*- mode: python ; coding: utf-8 -*-

added_files = [
        ('assets/about_dark.png', 'assets'),
        ('assets/about_light.png', 'assets'),
        ('assets/home_dark.png', 'assets'),
        ('assets/home_light.png', 'assets'),
        ('assets/off_switch.png', 'assets'),
        ('assets/on_switch.png', 'assets'),
        ('assets/settings_dark.png', 'assets'),
        ('assets/settings_light.png', 'assets'),
        ('assets/xpaste_logo.ico', 'assets'),
        ('assets/xpaste_logo.png', 'assets'),
        ('azure-ttk/azure.tcl', 'azure-ttk'),
        ('azure-ttk/theme/dark.tcl', 'azure-ttk/theme'),
        ('azure-ttk/theme/light.tcl', 'azure-ttk/theme'),
        ('azure-ttk/theme/dark/combo-button-basic.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/combo-button-focus.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/combo-button-hover.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/down.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/down-accent.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/rect-basic.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/rect-hover.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/up.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/up-accent.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/box-accent.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/box-basic.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/box-disabled.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/box-hover.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/box-invalid.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/button-hover.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/button-hover-transparent.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/card.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/check-accent.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/check-basic.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/check-hover.png', 'azure-ttk/theme/dark'),
        ('azure-ttk/theme/dark/combo-button-basic.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/combo-button-focus.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/combo-button-hover.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/down.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/down-accent.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/rect-basic.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/rect-hover.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/up.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/up-accent.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/box-accent.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/box-basic.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/box-disabled.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/box-hover.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/box-invalid.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/button-hover.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/card.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/check-accent.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/check-basic.png', 'azure-ttk/theme/light'),
        ('azure-ttk/theme/light/check-hover.png', 'azure-ttk/theme/light')
    ]

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=added_files,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='xPaste',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/xpaste_logo.ico'
)
